model:
  name: 'ieee3modalPart'
  pretrained: True
  # load_weights: r"E:\reidCode\AAAI 2022-master\log\ablation_new\p6_CIM_GateSumOri_3M_NonLocal\model\model.pth.tar-50"

data:
  type: 'image'
  sources: ['RGBNT201']
  targets: ['RGBNT201']
  height: 256
  width: 128
  combineall: False
  workers: 0
  transforms: ['random_flip']
  save_dir: 'log\ablation_new\p6_CIM_GateSumOri_3M_NonLocal'

loss:
  name: 'margin'
  softmax:
    label_smooth: True
  ieee_margin: 1
  weight_m: 1.0
  weight_x: 1.0

sampler:
  train_sampler: 'RandomIdentitySampler'
  num_instances: 4

train:
  optim: 'sgd'
  lr: 0.001
  max_epoch: 60
  batch_size: 8
  fixbase_epoch: 0
  open_layers: ['classifier_R', 'classifier_N', 'classifier_T']
  lr_scheduler: 'multi_step'
  stepsize: [20, 40]
  print_freq: 90

test:
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  visrank: False
  eval_freq: 5
  ranks: [1, 5, 10]
  rerank: False

